In [1]:
# 勾配降下法をtensorFlowで実践してみる
# テキスト上は手動、自動微分での手法が載っているが、オプティマイザを使えばそのようなものは不要なためここではオプティマイザを最初から使う
# オプティマイザは最適化手法のこと
# 勾配降下法一つをとってもたくさんのオプティマイザが用意されているよう。　tensorflow.train.AdamOptimizer　が良さげ？

# 以下お決まり設定
# To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "tensorflow"

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID, fig_id + ".png")
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)

In [4]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_california_housing

reset_graph()

housing = fetch_california_housing()
m, n = housing.data.shape
# m : housing.data.shape の行が設定される　20640
# n : housing.data.shape の列が設定される  8

# housing.data : データの中身を見れる(多次元配列)
# hoousing.data.shape : 配列の定義を見れる ここでは(20640,8) 20640インスタンス、特徴量8個

In [5]:
# 勾配降下法はスケーリングが重要なのでまずはスケーリングを行う。手法はお任せ。ここではscikit-learnで実施する
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_housing_data = scaler.fit_transform(housing.data) # housing.data を指定してスケーリングを行う
scaled_housing_data_plus_bias = np.c_[np.ones((m, 1)), scaled_housing_data]
# np.ones((m, 1)) : [1.]の20640個の配列
# np.c_ : 行列の連結
# np.c_[np.ones((m, 1)), housing.data] : [1., housing.dataの特徴量(8個)] の20640インスタンスのnumpy配列が出来上がる
# 先頭にバイアスとして　１　が設定されるnumpy配列ができているということ

In [6]:
# axis = 0 : 列ごと
# axis = 1 : 行ごと

print(scaled_housing_data_plus_bias.mean(axis=0)) # 列ごとの平均値
# scaled_housing_data_plus_bias : [[1.,...]] の　(20640,9) のnumpy配列
# 列ごとの平均値は一つ目の特徴量は1固定なので1、以降の特徴量はその値による

print(scaled_housing_data_plus_bias.mean(axis=1)) # 行ごとの平均値
# こちらは行ごとの平均値であるため、インスタンスごとの平均値をもっている

print(scaled_housing_data_plus_bias.mean()) # 平均値
# インスタンスすべての平均値

print(scaled_housing_data_plus_bias.shape) # numpy配列の情報

[ 1.00000000e+00  6.60969987e-17  5.50808322e-18  6.60969987e-17
 -1.06030602e-16 -1.10161664e-17  3.44255201e-18 -1.07958431e-15
 -8.52651283e-15]
[ 0.38915536  0.36424355  0.5116157  ... -0.06612179 -0.06360587
  0.01359031]
0.11111111111111005
(20640, 9)


In [27]:
reset_graph()

n_epochs = 1000
learning_rate = 0.01

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0, seed=42), name="theta")
# random_uniform : 与えた形状と範囲に基づいてランダム値を格納するテンソルを生成する
# tf.random_uniform([n + 1, 1]) では (9,1)のnumpy配列　ここでは操作名"theata" として(9,1)のnumpy配列 最小値-1,最大値1 で作成
# theataが重みをもった特徴量ベクトルになる

#y_pred = tf.matmul(X, theta, name="predictions")
# tf.matmul : 行列積  ここでは訓練データ(20640,9)と(9,1)の行列積となる python 3.5 からは以下の書き方がある
# ここで行列積を出しているのは入力となるnumpy配列の特徴量ベクトルと重み更新のためのtheata特徴量ベクトルをかけることにより予測値を出すため
#python3.5からの簡単な記載
y_pred = X @ theta

error = y_pred - y # 上で予測した値とラベルデータを比較して誤差をMSEに流し込む
mse = tf.reduce_mean(tf.square(error), name="mse") # 平均二乗誤差であるMSEの定義をしている

In [28]:
# オプティマイザとして勾配降下法のオプティマイザを設定
# 学習率をの設定をしていることに注意
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)

# 上で作成した誤差関数を訓練用に設定している
training_op = optimizer.minimize(mse)

In [29]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)

    for epoch in range(n_epochs):
        if epoch % 100 == 0: # 100 回終わるごとにメッセージを表示しているだけ
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    
    best_theta = theta.eval() # theataは重み更新の特徴量ベクトルなのでこの値が「重み」となっている

print("Best theta:")
print(best_theta)

Epoch 0 MSE = 9.161543
Epoch 100 MSE = 0.7145006
Epoch 200 MSE = 0.566705
Epoch 300 MSE = 0.5555719
Epoch 400 MSE = 0.5488112
Epoch 500 MSE = 0.5436362
Epoch 600 MSE = 0.5396294
Epoch 700 MSE = 0.5365092
Epoch 800 MSE = 0.5340678
Epoch 900 MSE = 0.5321474
Best theta:
[[ 2.0685525 ]
 [ 0.8874027 ]
 [ 0.14401658]
 [-0.34770882]
 [ 0.36178368]
 [ 0.00393811]
 [-0.04269556]
 [-0.6614528 ]
 [-0.6375277 ]]


In [33]:
# tf.placeholder　を使う
# tf.placeholder(tf.type_name, shape=(x,y),name)

# データが格納される入れ物として作用する。
# 実行時に値の指摘ができる。これを使用することでミニバッチ勾配降下法が作成できる

reset_graph()

A = tf.placeholder(tf.float32, shape=(None, 3)) # None は任意。実行時に指定できるということ
# この例では数値型の[任意の行,3列]　を実行時に与える

B = A + 5
with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A: [[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict={A: [[4, 5, 6], [7, 8, 9]]})

print(B_val_1)
# Aには[[1,2,3]]が入っているんので各値に5が加算される

[[6. 7. 8.]]


In [34]:
B_val_2
# Aには [[4, 5, 6], [7, 8, 9]]　が入っているので各値に5が加算される

array([[ 9., 10., 11.],
       [12., 13., 14.]], dtype=float32)

In [35]:
# ミニバッチ勾配降下法をtensofFlowで実装してみる
# placeholderを活用する
n_epochs = 1000
learning_rate = 0.01

In [36]:
reset_graph()

X = tf.placeholder(tf.float32, shape=(None, n + 1), name="X") # 定数ではなくplaceholderとして定義 nは特徴量数8なのでshape(none,9)となる
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")

In [38]:
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0, seed=42), name="theta")
y_pred = X @ theta
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()

In [39]:
n_epochs = 10

In [40]:
batch_size = 100
n_batches = int(np.ceil(m / batch_size)) # np.ceil() 計算結果の小数を切り上げ　この例では np.ceil(20640 / 100) で切り上げということ

In [41]:
# トレーニングバッチ内のインスタンス間に相関がないことを確認するために、各エポックでトレーニングデータをシャッフルする
def fetch_batch(epoch, batch_index, batch_size):
    np.random.seed(epoch * n_batches + batch_index)  # not shown in the book
    indices = np.random.randint(m, size=batch_size)  # not shown
    X_batch = scaled_housing_data_plus_bias[indices] # not shown
    y_batch = housing.target.reshape(-1, 1)[indices] # not shown
    return X_batch, y_batch

with tf.Session() as sess:
    sess.run(init)

    for epoch in range(n_epochs):
        for batch_index in range(n_batches):
            X_batch, y_batch = fetch_batch(epoch, batch_index, batch_size) # シャッフルされた訓練データ、ラベルデータを取得する
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch}) # 取得したデータでトレーニング

    best_theta = theta.eval()

In [42]:
best_theta

array([[ 2.0703337 ],
       [ 0.8637145 ],
       [ 0.12255151],
       [-0.31211874],
       [ 0.38510373],
       [ 0.00434168],
       [-0.01232954],
       [-0.83376896],
       [-0.8030471 ]], dtype=float32)

In [ ]:
# モデルの保存と復元
# モデルをほかのプログラムで使用したり、比較するために使う。
# 訓練中に適宜保存することでクラッシュ後のリラン対応も行える